services:
  log_analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: log_analyzer_container
    volumes:
      - ./logs:/app/logs
      - ./reports:/app/reports
      - ./sample_config.json:/app/sample_config.json
      - ./output_logs:/app/output_logs
    command: ["poetry","--directory", "/app", "run", "python", "-m", "app.main", "--config", "/app/sample_config.json"]
